### ISSUE TITLE
Please create requirements.txt (builtwith,ipapi)

### ISSUE THREAD

**Issue by cipher387** [Q0120S/NoobWebHunter#1]
1.

File "NoobWebHunter.py", line 6, in <module>
    from modules import cms, cloudflare, traceroute, reverseip, portscan, iplocation, httpheader, findsharedns, finder, whois, wordpress, robots, dnslookup
  File "/workspace/NoobWebHunter/modules/cms.py", line 1, in <module>
    import builtwith
ModuleNotFoundError: No module named 'builtwith'

2.

File "NoobWebHunter.py", line 6, in <module>
    from modules import cms, cloudflare, traceroute, reverseip, portscan, iplocation, httpheader, findsharedns, finder, whois, wordpress, robots, dnslookup
  File "/workspace/NoobWebHunter/modules/iplocation.py", line 2, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi'

**Comment by Q0120S** [comment]
> File "NoobWebHunter.py", line 6, in from modules import cms, cloudflare, traceroute, reverseip, portscan, iplocation, httpheader, findsharedns, finder, whois, wordpress, robots, dnslookup File "/workspace/NoobWebHunter/modules/cms.py", line 1, in import builtwith ModuleNotFoundError: No module named 'builtwith'
> 
> 
> File "NoobWebHunter.py", line 6, in from modules import cms, cloudflare, traceroute, reverseip, portscan, iplocation, httpheader, findsharedns, finder, whois, wordpress, robots, dnslookup File "/workspace/NoobWebHunter/modules/iplocation.py", line 2, in import ipapi ModuleNotFoundError: No module named 'ipapi'

Did you clone all files from NoobWebHunter Repository?

**Comment by Q0120S** [comment]
> File "NoobWebHunter.py", line 6, in from modules import cms, cloudflare, traceroute, reverseip, portscan, iplocation, httpheader, findsharedns, finder, whois, wordpress, robots, dnslookup File "/workspace/NoobWebHunter/modules/cms.py", line 1, in import builtwith ModuleNotFoundError: No module named 'builtwith'
> 
> 
> File "NoobWebHunter.py", line 6, in from modules import cms, cloudflare, traceroute, reverseip, portscan, iplocation, httpheader, findsharedns, finder, whois, wordpress, robots, dnslookup File "/workspace/NoobWebHunter/modules/iplocation.py", line 2, in import ipapi ModuleNotFoundError: No module named 'ipapi'

I fixed that issue. Now you can use it without any problem.
